title = "Eldaniz Babayev"
baseURL = 'https://debanwita27.github.io'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID


# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30
    [[menu.main]]
    pageRef="logs"
    name = 'Logs'
    url = '/logs/'
    weight = 40

[params]
  sitename = "Eldaniz Babayev"
  defaultColor = "dark" # set default color mode: dark or light
  description = "Minimal Hugo blog theme with light and dark mode support"

[params.author]
  avatar = "me.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Eldaniz Babayev"
  name = "Eldaniz Babayev"
  description = "Robotics student at Poland who loves to broaden his knowledge about embedded level development. Mostly specific topics, such as Linux kernel development, understanding errors on physical device level, and Rust language on embedded devices. "

[[params.socialIcons]]
name = "github"
url = "https://github.com/eld4niz"

[[params.socialIcons]]
name = "linkedin"
url = "http://www.linkedin.com/in/eldaniiz/"

[[params.socialIcons]]
name = "email"
url = "mailto:eldanizbabayev@proton.me"
